# Generated by Django 5.2.4 on 2025-08-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                default="", help_text="Name of the company/organization", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, default="", help_text="Department/Division", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True, default="", help_text="User's job title", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["company_name"], name="auth_users_company_ddf8ad_idx"
            ),
        ),
    ]
