# Generated by Django 5.2.4 on 2025-08-07 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_user_company_name_user_department_user_job_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("password_hash", models.CharField(max_length=128)),
                ("otp_code", models.CharField(max_length=6)),
                ("otp_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "pending_signups",
                "indexes": [
                    models.Index(fields=["email"], name="pending_sig_email_9d6145_idx"),
                    models.Index(
                        fields=["otp_code"], name="pending_sig_otp_cod_110aea_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="pending_sig_expires_e86736_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="pending_sig_is_veri_62566f_idx"
                    ),
                ],
            },
        ),
    ]
