# Generated by Django 5.2.4 on 2025-08-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_pendingsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
