# Generated by Django 5.2.4 on 2025-08-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_usersession_session_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingSignup",
        ),
    ]
