# Generated by Django 5.2.4 on 2025-08-10 06:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_delete_pendingsignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurePasswordReset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("email_sent", "Email Verification Sent"),
                            (
                                "email_verified",
                                "Email Verified - Awaiting Security Questions",
                            ),
                            ("security_verified", "Security Questions Verified"),
                            ("otp_sent", "OTP Sent for Final Verification"),
                            ("otp_verified", "OTP Verified - Ready for Password Reset"),
                            ("completed", "Password Reset Completed"),
                            ("expired", "Request Expired"),
                            ("blocked", "Request Blocked Due to Security"),
                        ],
                        default="email_sent",
                        max_length=20,
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(max_length=64, unique=True),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("security_question_attempts", models.PositiveIntegerField(default=0)),
                ("security_verified_at", models.DateTimeField(blank=True, null=True)),
                ("otp_code", models.CharField(blank=True, max_length=6)),
                ("otp_attempts", models.PositiveIntegerField(default=0)),
                ("otp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("password_reset_token", models.CharField(blank=True, max_length=64)),
                (
                    "password_reset_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicious_reasons", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "secure_password_resets",
            },
        ),
        migrations.CreateModel(
            name="SecurityQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer_hash", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "security_questions",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="auth_users_email_9c7e62_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="auth_users_role_8a5295_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="auth_users_is_emai_8cbe6f_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="auth_users_company_ddf8ad_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="last_password_reset_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.AddField(
            model_name="securepasswordreset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secure_password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="securepasswordreset",
            index=models.Index(
                fields=["user", "current_step"], name="secure_pass_user_id_70abfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securepasswordreset",
            index=models.Index(
                fields=["email_verification_token"],
                name="secure_pass_email_v_9ffb6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securepasswordreset",
            index=models.Index(
                fields=["password_reset_token"], name="secure_pass_passwor_1f520a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securepasswordreset",
            index=models.Index(
                fields=["expires_at"], name="secure_pass_expires_7cc1dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="securityquestion",
            unique_together={("user", "question")},
        ),
    ]
