# Generated by Django 5.2.4 on 2025-08-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0006_securepasswordreset_securityquestion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securepasswordreset",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="securityquestion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="securityquestion",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_password_reset_request",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_changed_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_reset_attempts",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="auth_users_email_9c7e62_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="auth_users_role_8a5295_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_email_verified"], name="auth_users_is_emai_8cbe6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["company_name"], name="auth_users_company_ddf8ad_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_users",
        ),
        migrations.DeleteModel(
            name="SecurePasswordReset",
        ),
        migrations.DeleteModel(
            name="SecurityQuestion",
        ),
    ]
