# Generated by Django 5.2.4 on 2025-08-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_securepasswordreset_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresettoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("activation", "Account Activation"),
                    ("reset", "Password Reset"),
                ],
                default="reset",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_password_reset",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_required",
            field=models.BooleanField(
                default=False, help_text="User must reset password on next login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, help_text="User can log in"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "token_type", "is_used"],
                name="password_re_user_id_b7878d_idx",
            ),
        ),
    ]
