# Generated by Django 5.2.4 on 2025-08-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_passwordresettoken_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications"
                    ),
                ),
                (
                    "security_alerts",
                    models.BooleanField(
                        default=True, help_text="Receive security alerts"
                    ),
                ),
                (
                    "product_updates",
                    models.BooleanField(
                        default=False, help_text="Receive product update notifications"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False, help_text="Receive marketing emails"
                    ),
                ),
                (
                    "login_notifications",
                    models.BooleanField(
                        default=True, help_text="Get notified of new logins"
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("team", "Team Only"),
                            ("private", "Private"),
                        ],
                        default="team",
                        help_text="Who can see your profile",
                        max_length=10,
                    ),
                ),
                (
                    "activity_tracking",
                    models.BooleanField(
                        default=True, help_text="Track activity for analytics"
                    ),
                ),
                (
                    "analytics_sharing",
                    models.BooleanField(
                        default=False, help_text="Share anonymized analytics data"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Español"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                            ("zh", "中文"),
                            ("ja", "日本語"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                            ("DD-MM-YYYY", "DD-MM-YYYY"),
                            ("MM-DD-YYYY", "MM-DD-YYYY"),
                        ],
                        default="MM/DD/YYYY",
                        max_length=15,
                    ),
                ),
                (
                    "default_view",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("analytics", "Analytics"),
                            ("tools", "Security Tools"),
                            ("reports", "Reports"),
                        ],
                        default="dashboard",
                        max_length=20,
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable two-factor authentication"
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (60, "1 hour"),
                            (120, "2 hours"),
                            (240, "4 hours"),
                            (480, "8 hours"),
                            (720, "12 hours"),
                            (1440, "24 hours"),
                        ],
                        default=60,
                        help_text="Session timeout in minutes",
                    ),
                ),
                (
                    "advanced_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Advanced user preferences"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("settings_change", "Settings Change"),
                            ("password_change", "Password Change"),
                            ("profile_update", "Profile Update"),
                            ("data_export", "Data Export"),
                            ("data_import", "Data Import"),
                            ("security_event", "Security Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activity_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="user_activi_user_id_82c355_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="user_activi_action_0ebaa4_idx",
                    ),
                ],
            },
        ),
    ]
