# Generated by Django 4.2.7 on 2025-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_remove_mfa_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpverification",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="delivery_method",
            field=models.CharField(
                choices=[("email", "Email")], default="email", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("signup", "Signup Verification"),
                    ("login", "Login Verification"),
                    ("password_reset", "Password Reset"),
                    ("email_change", "Email Change"),
                ],
                max_length=20,
            ),
        ),
    ]
