# Generated by Django 4.2.7 on 2025-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_remove_otpverification_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="custom_session_timeout",
            field=models.IntegerField(
                default=3600,
                help_text="Custom session timeout in seconds (used when session_timeout is 0)",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="session_timeout",
            field=models.IntegerField(
                choices=[
                    (10, "10 seconds"),
                    (60, "1 minute"),
                    (300, "5 minutes"),
                    (600, "10 minutes"),
                    (3600, "1 hour"),
                    (7200, "2 hours"),
                    (14400, "4 hours"),
                    (28800, "8 hours"),
                    (43200, "12 hours"),
                    (86400, "24 hours"),
                    (0, "Custom"),
                ],
                default=3600,
                help_text="Session timeout in seconds",
            ),
        ),
    ]
