# Generated by Django 5.2.5 on 2025-09-26 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_update_session_timeout_to_5_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='', help_text='Name of the company/organization (legacy field)', max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the company', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Company description')),
                ('email_domain', models.CharField(blank=True, help_text='Company email domain (e.g., company.com)', max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Company phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Company address')),
                ('enabled_tools', models.JSONField(default=list, help_text='List of enabled tools for this company')),
                ('is_active', models.BooleanField(default=True, help_text='Company is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Associated company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.company'),
        ),
        migrations.CreateModel(
            name='CompanyToolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('gsuite', 'G Suite'), ('mdm', 'MDM'), ('siem', 'SIEM'), ('edr', 'EDR'), ('meraki', 'Meraki'), ('sonicwall', 'SonicWall')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=True, help_text='Can view tool data')),
                ('can_upload', models.BooleanField(default=True, help_text='Can upload data')),
                ('can_analyze', models.BooleanField(default=True, help_text='Can run analysis')),
                ('can_export', models.BooleanField(default=True, help_text='Can export data')),
                ('can_manage', models.BooleanField(default=False, help_text='Can manage tool settings')),
                ('data_retention_days', models.IntegerField(default=365, help_text='Days to retain data (0 = unlimited)')),
                ('max_upload_size_mb', models.IntegerField(default=100, help_text='Maximum upload size in MB')),
                ('max_records_per_upload', models.IntegerField(default=100000, help_text='Maximum records per upload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_permissions', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tool_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_tool_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email_domain'], name='companies_email_d_e67f37_idx'),
        ),
        migrations.AddIndex(
            model_name='companytoolpermission',
            index=models.Index(fields=['company', 'tool_type'], name='company_too_company_4c3f32_idx'),
        ),
        migrations.AddIndex(
            model_name='companytoolpermission',
            index=models.Index(fields=['is_enabled'], name='company_too_is_enab_3c9742_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companytoolpermission',
            unique_together={('company', 'tool_type')},
        ),
    ]
