# Generated by Django 5.2.5 on 2025-10-06 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_create_company_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFACode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mfa_codes',
                'indexes': [models.Index(fields=['user', 'is_used'], name='mfa_codes_user_id_5e09d9_idx'), models.Index(fields=['code'], name='mfa_codes_code_98ebae_idx'), models.Index(fields=['expires_at'], name='mfa_codes_expires_2a908b_idx'), models.Index(fields=['last_sent_at'], name='mfa_codes_last_se_db3815_idx')],
            },
        ),
    ]
