# Generated by Django 5.2.5 on 2025-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_mfacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=10, help_text='Maximum number of users allowed for this company'),
        ),
    ]
