# Generated by Django 5.2.5 on 2025-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_add_max_users_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('general', 'General User'), ('admin', 'Admin'), ('master_admin', 'Master Admin'), ('super_admin', 'Super Admin')], default='general', max_length=20),
        ),
    ]
