# Generated by Django 5.2.4 on 2025-07-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityDataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("gsuite", "G Suite"),
                            ("mdm", "MDM"),
                            ("siem", "SIEM"),
                            ("edr", "EDR"),
                            ("meraki", "Meraki"),
                            ("sonicwall", "SonicWall"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_data", models.JSONField(default=dict)),
                ("sheet_names", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tool.securitydataupload",
                    ),
                ),
            ],
        ),
    ]
