# Generated by Django 5.2.4 on 2025-08-10 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0002_enhanced_data_persistence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processinglog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveConstraint(
            model_name="securitydataupload",
            name="unique_active_tool_per_company",
        ),
        migrations.AlterField(
            model_name="dataaccesslog",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("download", "Download"),
                    ("analyze", "Analyze"),
                ],
                default="view",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processinglog",
            name="level",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                default="INFO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="securitydataupload",
            name="company_name",
            field=models.CharField(
                blank=True, default="default_company", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(
                fields=["upload", "accessed_at"], name="tool_dataac_upload__71010f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(
                fields=["user", "accessed_at"], name="tool_dataac_user_id_46ccf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datanotification",
            index=models.Index(
                fields=["recipient", "is_read"], name="tool_datano_recipie_32c340_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datanotification",
            index=models.Index(
                fields=["created_at"], name="tool_datano_created_aa0bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["upload", "timestamp"], name="tool_proces_upload__df8a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processinglog",
            index=models.Index(
                fields=["level", "timestamp"], name="tool_proces_level_c53d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydataupload",
            index=models.Index(
                fields=["tool_type", "company_name", "is_active"],
                name="tool_securi_tool_ty_dcc0f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitydataupload",
            index=models.Index(
                fields=["uploaded_at"], name="tool_securi_uploade_603afd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydataupload",
            index=models.Index(fields=["status"], name="tool_securi_status_82b0a0_idx"),
        ),
    ]
