# Generated by Django 5.2.4 on 2025-08-12 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0003_alter_processinglog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dataaccesslog",
            name="data_company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="is_cross_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="user_company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="dataaccesslog",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("download", "Download"),
                    ("analyze", "Analyze"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                ],
                default="view",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(
                fields=["is_cross_company"], name="tool_dataac_is_cros_0478b1_idx"
            ),
        ),
    ]
