# Generated by Django 5.2.4 on 2025-08-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_add_production_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitydataupload',
            name='tool_securitydataupload_hash_company_tool_idx',
        ),
        migrations.RemoveIndex(
            model_name='securitydataupload',
            name='tool_securitydataupload_company_active_tool_idx',
        ),
    ]
