# Generated by Django 4.2.7 on 2025-08-28 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "tool",
            "0006_remove_securitydataupload_tool_securitydataupload_hash_company_tool_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anomaly_date", models.DateField(db_index=True)),
                ("anomaly_score", models.FloatField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("feature_values", models.JSONField(default=dict)),
                ("feature_importance", models.JSONField(default=dict)),
                ("description", models.TextField()),
                ("summary", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("investigating", "Under Investigation"),
                            ("confirmed", "Confirmed"),
                            ("false_positive", "False Positive"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                (
                    "company_name",
                    models.CharField(
                        db_index=True, default="default_company", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("gsuite", "G Suite"),
                            ("mdm", "MDM"),
                            ("siem", "SIEM"),
                            ("edr", "EDR"),
                            ("meraki", "Meraki"),
                            ("sonicwall", "SonicWall"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("isolation_forest", "Isolation Forest"),
                            ("one_class_svm", "One-Class SVM"),
                            ("autoencoder", "Autoencoder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_file_path", models.CharField(blank=True, max_length=255)),
                ("feature_columns", models.JSONField(default=list)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("training_data_size", models.IntegerField(default=0)),
                ("contamination_rate", models.FloatField(default=0.1)),
                ("training_accuracy", models.FloatField(blank=True, null=True)),
                ("validation_score", models.FloatField(blank=True, null=True)),
                ("false_positive_rate", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("trained", "Trained"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "company_name",
                    models.CharField(
                        db_index=True, default="default_company", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyTrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("gsuite", "G Suite"),
                            ("mdm", "MDM"),
                            ("siem", "SIEM"),
                            ("edr", "EDR"),
                            ("meraki", "Meraki"),
                            ("sonicwall", "SonicWall"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("isolation_forest", "Isolation Forest"),
                            ("one_class_svm", "One-Class SVM"),
                            ("autoencoder", "Autoencoder"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="default_company", max_length=255),
                ),
                ("training_data_size", models.IntegerField(default=0)),
                ("contamination_rate", models.FloatField(default=0.1)),
                ("hyperparameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                ("training_metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trained_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="tool.anomalymodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="anomalymodel",
            index=models.Index(
                fields=["tool_type", "company_name", "is_active"],
                name="tool_anomal_tool_ty_6dd498_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalymodel",
            index=models.Index(
                fields=["algorithm", "status"], name="tool_anomal_algorit_a1479e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="anomalymodel",
            unique_together={("tool_type", "company_name", "algorithm")},
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="investigated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigated_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="model_used",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="tool.anomalymodel",
            ),
        ),
        migrations.AddField(
            model_name="anomalydetection",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="tool.securitydataupload",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalytrainingjob",
            index=models.Index(
                fields=["status", "created_at"], name="tool_anomal_status_a72dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalytrainingjob",
            index=models.Index(
                fields=["tool_type", "company_name"],
                name="tool_anomal_tool_ty_cc73eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["company_name", "anomaly_date"],
                name="tool_anomal_company_e3ba8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["severity", "status"], name="tool_anomal_severit_2243ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(
                fields=["upload", "created_at"], name="tool_anomal_upload__3458b8_idx"
            ),
        ),
    ]
