# Generated by Django 5.2.5 on 2025-09-02 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0008_chatconversation_chatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SOCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("individual_tool", "Individual Tool Report"),
                            ("combined_tools", "Combined Tools Report"),
                            ("executive_summary", "Executive Summary"),
                            ("incident_report", "Incident Report"),
                            ("threat_analysis", "Threat Analysis Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("tool_types", models.JSONField(default=list)),
                ("executive_summary", models.TextField(blank=True)),
                ("monitoring_overview", models.TextField(blank=True)),
                ("incident_summary", models.TextField(blank=True)),
                ("critical_threat_analysis", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("kpi_metrics", models.JSONField(default=dict)),
                ("charts_config", models.JSONField(default=list)),
                ("appendix", models.TextField(blank=True)),
                ("report_period_start", models.DateField()),
                ("report_period_end", models.DateField()),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_model_used",
                    models.CharField(default="gemini-1.5-flash", max_length=50),
                ),
                ("generation_prompt", models.TextField(blank=True)),
                ("generation_time", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="default_company", max_length=255),
                ),
                ("exported_formats", models.JSONField(default=list)),
                ("last_exported", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_uploads",
                    models.ManyToManyField(
                        related_name="reports", to="tool.securitydataupload"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SOCReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("html", "HTML"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(default=0)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("export_settings", models.JSONField(default=dict)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="tool.socreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-exported_at"],
            },
        ),
        migrations.CreateModel(
            name="SOCReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive Summary"),
                            ("monitoring_overview", "Monitoring Overview"),
                            ("incident_summary", "Incident Summary"),
                            ("threat_analysis", "Critical Threat Analysis"),
                            ("kpi_metrics", "KPI Metrics"),
                            ("recommendations", "Recommendations"),
                            ("custom", "Custom Section"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("chart_data", models.JSONField(blank=True, default=dict)),
                ("chart_type", models.CharField(blank=True, max_length=50)),
                ("is_ai_generated", models.BooleanField(default=True)),
                ("manually_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tool.socreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "order"],
            },
        ),
        migrations.CreateModel(
            name="SOCReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Dashboard"),
                            ("technical", "Technical Analysis"),
                            ("compliance", "Compliance Report"),
                            ("incident_response", "Incident Response"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sections_config", models.JSONField(default=list)),
                ("default_charts", models.JSONField(default=list)),
                ("ai_prompts", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "company_name",
                    models.CharField(default="default_company", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="socreport",
            index=models.Index(
                fields=["company_name", "report_type", "status"],
                name="tool_socrep_company_faff04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socreport",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="tool_socrep_created_29d630_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socreport",
            index=models.Index(
                fields=["report_period_start", "report_period_end"],
                name="tool_socrep_report__f30f27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socreportexport",
            index=models.Index(
                fields=["report", "-exported_at"], name="tool_socrep_report__e0aaa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socreportexport",
            index=models.Index(
                fields=["exported_by", "-exported_at"],
                name="tool_socrep_exporte_f874d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socreportsection",
            index=models.Index(
                fields=["report", "order"], name="tool_socrep_report__8f55ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socreportsection",
            index=models.Index(
                fields=["section_type"], name="tool_socrep_section_76eab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socreporttemplate",
            index=models.Index(
                fields=["company_name", "is_active"],
                name="tool_socrep_company_6618f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="socreporttemplate",
            index=models.Index(
                fields=["template_type", "is_default"],
                name="tool_socrep_templat_7ff363_idx",
            ),
        ),
    ]
