# Generated by Django 4.2.7 on 2025-09-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0009_socreport_socreportexport_socreportsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socreportsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("executive_summary", "Executive Summary"),
                    ("incident_overview", "Incident Overview"),
                    ("performance_metrics", "Performance Metrics"),
                    ("threat_landscape", "Threat Landscape"),
                    ("monitoring_overview", "Monitoring Overview"),
                    ("incident_summary", "Incident Summary"),
                    ("threat_analysis", "Critical Threat Analysis"),
                    ("remediation_actions", "Remediation Actions"),
                    ("compliance", "Compliance Status"),
                    ("kpi_metrics", "KPI Metrics"),
                    ("recommendations", "Recommendations & Action Items"),
                    ("custom", "Custom Section"),
                ],
                max_length=20,
            ),
        ),
    ]
